export const GET_CART = "GET_CART";
export const SAVE_CART = "SAVE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_QUANTITY_CART_ITEM = "UPDATE_QUANTITY_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
